version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  qdrant_data: