import './globals.css';
import MantineProviderClient from '../components/MantineProviderClient';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MantineProviderClient>{children}</MantineProviderClient>
      </body>
    </html>
  )
}
